name: Compile Windows Installer

on: [push] # Triggers automatically whenever you save a file

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PySide6 and Nuitka dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt

      - name: Compile with Nuitka (CPU Stable MinGW64)
        run: |
          python -m nuitka --standalone --windows-console-mode=disable --mingw64 --assume-yes-for-downloads --output-dir=build --output-filename=app --include-data-dir=templates=templates run.py

      - name: Compile Setup Installer (Using Inno Setup)
        run: |
          iscc installer_config.iss

      - name: Upload Finished Installer to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: TDF-Encrypt-Installer
          path: installer_output/TDF-Encrypt.exe